### ISSUE TITLE
Add bobby-b-bot to r/classicwow

### ISSUE THREAD

**Issue by philmtd** [bobby-b-bot/reddit#2]
There are many freefolk in r/classicwow and we figured we might need Bobby B to help us out sometimes. It would be nice if you could add r/classicwow to the list of subreddits.

Recent proof, that freefolk exists there: https://www.reddit.com/r/classicwow/comments/c266dn/how_it_feels_jumping_back_into_classic_at_30/erig7mu/?context=8&depth=9

**Comment by fzanettini** [comment]
Since this is a WoW thematic sub, and the first rule of the sub is that the content should be related to WoW: Classic, is there any way to get the moderators approval for the bot? Just for transparency and avoiding the bot to be banned from the sub.

**Comment by philmtd** [comment]
I'll try to contact them.

**Comment by philmtd** [comment]
Asked the mods here: https://www.reddit.com/r/classicwow/comments/c266dn/how_it_feels_jumping_back_into_classic_at_30/erkk3kc/

I'll update if I get a reply there.

**Comment by fzanettini** [comment]
Thanks, I will wait for their approval.

**Comment by iDylo** [comment]
Huge fan of the bot - would love to have it in the subreddit. You can verify with me at u/iDylo if you’d like.

**Comment by fzanettini** [comment]
Thank you for your comments and for the approval. I have added the bot to r/classicwow on the following commit: d7a14e61a47ae3a61af3ce51adf5548bcbe10f77.
