### ISSUE TITLE
How about Bobby B comes onto GitHub?

### ISSUE THREAD

**Issue by Aniket-Pradhan** [bobby-b-bot/reddit#3]
Just had this awesome idea.

Let's keep this simple as well. We have Bobby B.  He monitors some repositories and comments on issues/PRs whenever he is summoned.

I would like to work on it. You up?

**Comment by Aniket-Pradhan** [comment]
Well. I sorta did something and made an app [here](https://github.com/apps/king-bobby-b-bot). If you want, have a look at it as well. :D

**Comment by fzanettini** [comment]
That looks great. Thank you!
